chunking:
  markdown_chunker:
    headers_to_split_on:
      - ["#", "Header 1"]
      - ["##", "Header 2"]
      - ["###", "Header 3"]

  json_chunker:
    chunk_size: 400

  code_chunker:
    chunk_size: 400
    chunk_overlap: 50

  recursive_chunker:
    chunk_size: 400
    chunk_overlap: 50
    separators:
      - "\n\n"
      - "\n"
      - " "
      - "."
      - ","
      - "\u200b"     # Zero-width space
      - "\uff0c"     # Fullwidth comma
      - "\u3001"     # Ideographic comma
      - "\uff0e"     # Fullwidth full stop
      - "\u3002"     # Ideographic full stop
      - ""

  content_type_to_chunker:
    text: recursive_chunker
    markdown: markdown_chunker
    json: json_chunker
    code: code_chunker
    image: null
    blob: null


embedding:
  text:
    type: replicate
    model: all-mpnet-base-v2
    normalize: true
  image:
    type: replicate
    model: clip
    input_size: 224
    normalize: true
  batch_size: 64


storaging:
  type: weaviate

  weaviate:
    deployment: local
    url: localhost
    api_key: null
    secure: false
    port: 8080
    distance: cosine


generation:
  type: openai
  model: gpt-4o
  context_limit: 120000


transcribing:
  type: replicate
  model: whisper


captioning:
  type: custom
  model: blip2


reranking:
  type: custom
  model: rerank-v1
  supported_modes:
    - text
    - images


asset_store:
  type: s3
  s3:
    bucket: bucket-name
    region: eu-central-1
    endpoint_url: http://localhost:9000
    overwrite: true
  local:
    root_dir: /local/dir
    overwrite: true
